modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    description='''
        Adds a configurable Trade Box block that allows players to purchase enchanted books
        using items defined in a JSON config file.
    '''

[[dependencies.tradebox]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tradebox]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
